name: Java CI/CD Pipeline to tomcat

on:
 push:
   branches: main

jobs:
  build :
    runs-on: [self-hosted, linux]
    steps:
      - name: checkout the code
        uses: actions/checkout@v7
        
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Ensure maven is installed
        run : |
           if ! command -v mvn &> /dev/null; then
            echo "Maven not found. Installing..."
            sudo dnf install -y maven
             else
               echo "Maven is already installed"
             fi
               mvn -version

      - name: Cache maven dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
          
      - name: Build with maven
        run: mvn clean package -DskipTests

      - name: upload war as artifact
        uses: actions/upload-artifact@v7
        with:
          name: myapp
          path: target/*.war

  deploy:
    needs: build
    runs-on: [self-hosted, linux]
    environment: production
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v8
        with:
          name: myapp
          
      - name: deploy war to tomcat
        run: |
          WAR_FILE=$(ls *.war)
          echo "Deploying war file to tomcat"
          echo "HOST: ${{ secrets.TOMCAT_HOST }}"
          echo "user: ${{ secrets.TOMCAT_USER }}"
          curl -v --upload-file "$WAR_FILE" \
          "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"
          
      - name: Verify deployment
        run: |
         curl -I http://${{ secrets.TOMCAT_HOST }}/myapp
          
          
            
