name: Java CI/CD Pipeline to tomcat

on:
 push:
   branches: main

jobs:
  build :
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v7
        
      - name: setup jdk
        uses: actions/setup-java@v6
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build with maven
        run: mvn clean package -DskipTests

      - name: upload war as artifact
        uses: actions/upload-artifact@v7
        with:
          name: myapp
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Download the artifact
        uses: actions/download-artifact@v8
        with:
          name: myapp
          
      - name: deploy war to tomcat
        run: |
          WAR_FILE=$(ls *.war)
          echo "Deploying war file to tomcat"
          echo "HOST: ${{ secrets.TOMCAT_HOST }}"
          echo "user: ${{ secrets.TOMCAT_USER }}"
          curl -v --upload-file "$WAR_FILE" \
          "http://${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}@${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"
          
          
          
            
